# STATUS entries are bookkeeping, not conversation, and never count as messages.
STATUS_TYPES = {
    "STATUS", "STATUSCALLMISSEDAUDIO", "STATUSCALLMISSEDVIDEO",
    "STATUSCALLENDEDAUDIO", "STATUSCALLENDEDVIDEO",
    "STATUSERASEDMESSAGE", "STATUSSAVETOCAMERAROLL",
}

SNAP_TYPES = {"SNAP", "SNAPSAVED"}

CALL_TYPES = {
    "STATUSCALLMISSEDAUDIO", "STATUSCALLMISSEDVIDEO",
    "STATUSCALLENDEDAUDIO", "STATUSCALLENDEDVIDEO",
}
